

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

volumes:
  mongo_data:

